app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app_user:
    path:     /user
    defaults: { _controller: AppBundle:User:index }
    
app_admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }
    
app_edit:
    path:     /edit
    defaults: { _controller: AppBundle:Edit:index }
    
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    
