services:
    mp_user.form.type.login:
        class: MP\AppBundle\Form\Type\LoginFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mp_user_login_type }