services:
    mp_user.form.type.login:
        class: MP\AppBundle\Form\Type\LoginFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mp_user_login_type }
            
    security.authentication.failure_handler:
        class:  MP\AppBundle\Form\Handler\LoginFailureHandler
            
    security.authentication.success_handler:
        class:  MP\AppBundle\Form\Handler\LoginSuccessHandler
        arguments:  ['@router', '@doctrine.orm.entity_manager']
        
    security.logout.success_handler:
        class:  MP\AppBundle\Form\Handler\LogoutSuccessHandler
        arguments:  ['@router', '@doctrine.orm.entity_manager', '@security.token_storage']